artifacts_root : atrifacts




data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:  https://github.com/Abhishek-Mishra2408/dataset_repository/raw/refs/heads/main/Number_PlateRecognition%202.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion